version: "3"
services:
  keycloak:
    image: jboss/keycloak:12.0.2
    container_name: backoffice_keycloak
    restart: unless-stopped
    ports:
      - 8180:8080
      - 8443:8443
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
