version: "3"
services:
  keycloak:
    image: jboss/keycloak:12.0.2
    container_name: backoffice_keycloak
    restart: unless-stopped
    ports:
      - 8180:8080
    volumes:
      - ./config/keycloak:/opt/jboss/keycloak/realm-config
    command:
      [
        "-b",
        "0.0.0.0",
        "-Dkeycloak.migration.action=import",
        "-Dkeycloak.migration.provider=dir",
        "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config",
        "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING",
        "-Dkeycloak.profile.feature.upload_scripts=enabled",
      ]
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: current
