version: "3"
services:
  keycloak:
    image: jboss/keycloak:12.0.2
    container_name: backoffice_keycloak
    restart: unless-stopped
    ports:
      - 8180:8080
    volumes:
      - ./config/keycloak/realm-export.json:/tmp/realm.json
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_IMPORT: /tmp/realm.json
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: current
